PREP(doArtillery);
PREP(doAssaultUnitReset);
PREP(sideHasArtillery);
PREP(taskArtillery);
PREP(taskArtilleryRegister);
PREP(taskAssault);
PREP(taskCamp);
PREP(taskCQB);
PREP(taskCreep);
PREP(taskGarrison);
PREP(taskHunt);
PREP(taskPatrol);
PREP(taskReset);
PREP(taskRush);

SUBPREP(Modules,moduleArtillery);
SUBPREP(Modules,moduleArtilleryRegister);
SUBPREP(Modules,moduleAssault);
SUBPREP(Modules,moduleCamp);
SUBPREP(Modules,moduleCQB);
SUBPREP(Modules,moduleCreep);
SUBPREP(Modules,moduleGarrison);
SUBPREP(Modules,moduleHunt);
SUBPREP(Modules,modulePatrol);
SUBPREP(Modules,moduleReset);
SUBPREP(Modules,moduleRush);
SUBPREP(Modules,moduleTarget);


SUBPREP(ZEN,setArtilleryRegister);
SUBPREP(ZEN,setCamp);
SUBPREP(ZEN,setCQB);
SUBPREP(ZEN,setCreep);
SUBPREP(ZEN,setGarrison);
SUBPREP(ZEN,setHunt);
SUBPREP(ZEN,setPatrol);
SUBPREP(ZEN,setReset);
SUBPREP(ZEN,setRush);
SUBPREP(ZEN,setTarget);
